#!/bin/bash

# IPTV frontend for the new router firmware (>=8.C.D.9). Takes the channel ID
# as argument. If the proper interface is not connected, falls back to web
# stream.
#
# Arguments:
# 
# -a             - force alternate (web) stream
# -i <interface> - specify network interface
# -c <filename>  - dump to file

IPTV_IF=enp12s0
IPTV_NET="^192.168.1.101"

function get_conf_field {
	egrep "^$CHID[[:space:]]" $CONFFN | awk "{print \$$1;}" | head -n1
}

function err_play {
	echo $1 >&2
	[ $URL_FB ] || {
		echo "No fallback URL specified for $CHID!" >&2
		exit 1
	}
	$PLAYER $URL_FB
	exit 0
}

function err {
	echo $1 >&2
	exit 1
}

while getopts "ac:i:" OPT; do
        case $OPT in
                a ) ALTSTREAM=1 ;;
                c ) CAPFILE=$OPTARG ;;
				i ) IF=$OPTARG ;;
        esac
done

for i in $(seq 1 $(($OPTIND-1)))
	do shift; done

CONFFN="$(dirname $0)/../data/iptvrc"
DEFAULTPLFN="$(dirname $0)/../data/iptv.m3u"
IF=${IF-$IPTV_IF}
PLAYER=vlc

CHID=$(awk "/^$1[[:space:]]/ {print \$1;}" $CONFFN)
URL=$(get_conf_field 2)
URL_FB=$(get_conf_field 3)
	
LOCAL_IP=$(ip a show $IF | perl -nle 'print $1 if /inet\s+((?:\d{1,3}\.?){4})/')

[ $CHID ] || {\
	URL_FB=$DEFAULTPLFN
	err_play "No channel ID passed, falling back to default playlist"
}

[ $ALTSTREAM ] &&\
	err_play "Web stream requested"
[ $LOCAL_IP ] ||\
	err_play "Cannot determine local IP address for $IF, falling back to web stream"
echo $LOCAL_IP | egrep -q "$IPTV_NET" ||\
	err_play "$IF is not on the IPTV subnet, falling back to web stream"

shift

if [[ $CAPFILE ]]; then
	mplayer $URL -dumpstream -dumpfile $CAPFILE
else
	$PLAYER --sub-track 0 --deinterlace -1 --deinterlace-mode yadif2x $* $URL
fi

