#!/bin/bash

# Check if there are full-screen windows with title matching a pattern, in
# which case disable power management. Useful for running as a frequent cron 
# job or from a periodic script.

IFS=$"\n"; WMATCH=$(cat <<-EOF
	vlc media player
	plugin-container
	firefox
	mpv
EOF
);

SCRGEOMS=$(xrandr | fgrep connected |\
	perl -nle 'print $1 if /(\d{3,4}x\d{3,4}\+0\+0)/;')
IFS=" "
N_FS=$(xwininfo -root -tree |\
	perl -nle 's/^\s+//; print if /^0x[[:xdigit:]]+\s\"/;' |\
	fgrep -if <(echo $WMATCH) | fgrep -f <(echo $SCRGEOMS) |\
	cut -d'"' -f2 | wc -l)

if [[ $N_FS -gt 0 ]]; then
	xset -dpms
else
	xset +dpms
fi

