#!/bin/bash

# Resize a window matching (regex) the title. Only on-screen windows
# are considered.

[ $3 ] || {
	echo "Usage: windowdim window_title width height" >&2
	exit
}

TITLE=$1
W=$2
H=$3

WROOT=$(xwininfo -root | fgrep Width | awk '{print $2}')
HROOT=$(xwininfo -root | fgrep Height | awk '{print $2}')
WID=$(
	xdotool search --onlyvisible --name "$TITLE" |\
	xargs -n1 xdotool getwindowgeometry |\
	awk '
		/Window/   { WID=$2 }
		/Position/ { split($2, XY, ","); X=XY[1]; Y=XY[2]; }
		/Geometry/ {
			split($2, WH, "x"); W=WH[1]; H=WH[2];
			if (X+W > 1 && Y+H > 1 && X < '$WROOT' && Y < '$HROOT')
				print WID;
		}
	'
)
N=$(echo $WID | tr " " "\n" | wc -l)

[ -z "$WID" ] && {
	echo "Cannot find window with title \"$TITLE\"" >&2
	exit
}
[[ $N > 1 ]] && {
	echo "Cowardly refusing to resize more than one matching window" >&2
	exit
}

xdotool windowsize $WID $W $H

