#!/usr/bin/perl

# Dump the contents of Storables serialized in a file, file names passed as
# command line arguments

use warnings;
use strict;

use Data::Dumper;
use Storable;

sub dmp {
	print Data::Dumper->Dump([shift]);
}

sub main {
	my @filenames = @ARGV;

	die("Pass file name as an argument\n")
		unless(@filenames);

	foreach my $fn (@filenames) {
		my $ref;
		
		die("File not accessible\n")
			unless(-r $fn);
		die("Storable::retrieve didn't return a valid reference\n")
			unless($ref = Storable::retrieve($fn));
		dmp($ref);
	}

	1;
}

main();

